### ISSUE TITLE
ArgumentParser.java 在内容结尾是转义引号时无法正常解析

### ISSUE THREAD

**Issue by 1689295608** [XIAYM-gh/Simple-Mirai-Bot#1]
内容为 `"awa\""` 时无法正确解析

当输入内容为 `"\"awa\" and \"qwq\""`时，返回的结果并不正确

预期：`["awa", and, "qwq"]`
得到的却是：`["awa\, and, "qwq"]`

![image](https://user-images.githubusercontent.com/50663849/184798381-decb7b63-93ab-43ed-bae9-5c98fcd22bf0.png)
![image](https://user-images.githubusercontent.com/50663849/184798552-095a0b9a-5c33-4621-9ea2-2c8bf273e3d0.png)

**Comment by XIAYM-gh** [comment]
草 等我明天摸到电脑我就改 ()
在外面旅游没法修 doge

**Comment by XIAYM-gh** [comment]
草 我是傻逼
第一个没加判断
这下改好了

**Comment by 1689295608** [comment]
然后又发现了新的问题：
在解析：`"\"1\" \"2\" " 3 " \"4\" \"5\""` 时
预期：`["1" "2" , 3,  "4" "5"]`
得到的却是：`["1" "2" 3 "4" "5"]`

目测.. 没有目测到什么好的建议，加油吧（

**Comment by 1689295608** [comment]
可以参考 MiraiBot 的 [MiraiCommand.java](https://github.com/1689295608/MiraiBot/blob/52eb43bfc9f7b4fe315b2cb794bbd5b9017a4c8b/src/main/java/com/windowx/miraibot/MiraiCommand.java#L821-L858) 试一下？
（已知性能不怎么高，但 能跑就行（）

**Comment by XIAYM-gh** [comment]
重写了一遍，发现在" Text "时解析仍然没用
目测为 String.split() 的问题
我再康康

**Comment by XIAYM-gh** [comment]
是它的问题
Input> \"1\" \"2\" " 3 " \"4\" \"5\"
Output: [\"1\", \"2\", ", 3, ", \"4\", \"5\"]

**Comment by 1689295608** [comment]
我表示疑问：你用空格来分割 带有空格的引号内容为什么就能在一起？

"1 2 \"3 \" 4".split(" ")
是: `[1, 2, "3, 4]`

**Comment by 1689295608** [comment]
> 是它的问题 Input> "1" "2" " 3 " "4" "5" Output: ["1", "2", ", 3, ", "4", "5"]

这才是 split 的正常行为。

**Comment by 1689295608** [comment]
引用某人的一个表情包的内容：“多找找自身原因吧”
这对你也是的。
面子并不大于一切，要学到东西而不是为了面子而不愿意接受新知识。

*如果你是从邮箱中看 issues 的话，请前往 Github 查看 edited 的内容*

**Comment by 1689295608** [comment]
对此，我的建议是：[MiraiCommand.java#L885-L921](https://github.com/1689295608/MiraiBot/blob/main/src/main/java/com/windowx/miraibot/MiraiCommand.java#L885-L921)

**Comment by XIAYM-gh** [comment]
我超

**Comment by 1689295608** [comment]
> 对此，我的建议是：[MiraiCommand.java#L885-L921](https://github.com/1689295608/MiraiBot/blob/main/src/main/java/com/windowx/miraibot/MiraiCommand.java#L885-L921)

刚才用 StringBuilder 将该方法的性能提升了 3500% 
现在这个方法运行时间大约需要 1ms

**Comment by XIAYM-gh** [comment]
我这自己实现了一个split。。还是有逗号的问题
麻了，我再改改

**Comment by 1689295608** [comment]
如果愿意的话，我可以帮你一起解决
*希望你能冷静一下*

**Comment by 1689295608** [comment]
算了，我觉得你还是更爱你的面子。

**Comment by 1689295608** [comment]
记得删 issues
